language: node_js
node_js:
  - "11.0.0"
env:
  matrix:
    - REACT=16.12.0

install:
  - npm install

script:
  - npm run test
after_success:
  - npm run coverage
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
